// function helloworld(nome){
//     console.log ("oiii," + nome)
// }

// helloworld("pedro")

// function soma(num1 , num2 ){
//     let resultado =num1+num2
//     console.log(resultado)
// };
// soma(22,29)

// function subtracao(num1 , num2 ){
//     let resultado =num1-num2
//     console.log(resultado)
// };
// subtracao(882,29)

function areatriangulo(numero1,numero2,numero3 ){
    let resultado = numero1*numero2/numero3
    console.log (resultado)
}
areatriangulo(10,11,2)